# Valid values: 'none', 'debug', 'info', 'warning', 'error', 'critical'
loglevel: info

# Options for 'shoot' command
shoot:
    # ISO sensitivity
    sensitivity: 80
    shutter_speed: 1/25
    zoom_level: 3
    dpi: auto

# Options for 'download' command
download:
    # Activated plugins
    plugins: [combine]
    # keep files on cameras after downloading
    keep: no

# Options for 'postprocess' command
postprocess:
    # Number of concurrent jobs
    jobs: auto

    # Filters to be applied in order
    filters: [autorotate, scantailor, pdfbeads, djvubind]

    # Rotation applied to images from left and right camera
    autorotate:
        left: -90
        right: 90

    # ScanTailor options, see `scantailor-cli --help`
    scantailor:
        autopilot: no
        rotate: no
        split_pages: yes
        deskew: yes
        content: yes
        margins: yes
        detection: content # not yet implemented
        content_detection: normal # not yet implemented
        auto_margins: no # not yet implemented
        margins: [2.5, 2.5, 2.5, 2.5] # top, right, bottom, left
        output_dpi: auto # not yet implemented
        color_mode: black_and_white # not yet implemented
        binarize_threshold: 0 # not yet implemented
        despeckle: normal # not yet implemented
        dewarp: no # not yet implemented

    # PDF output options, see `pdfbeads --help`
    pdfbeads:
        layout: SinglePage # not yet implemented
        mask_compression: jbig2 # not yet implemented
        jbig2_dict_size: 15 # not yet implemented
        bg_compression: jp2 # not yet implemented

    # DJVU output options, see `djvubind --help`
    djvubind:
        ocr: none
        tesseract_options: [] # not yet implemented
        cuneiform_options: [] # not yet implemented
